export enum Status {
  DESHABILITADO = 0,
  HABILITADO = 1,
  PENDIENTE = 2,
  RECHAZADO_POR_TECNICO = 3,
  CONTRAOFERTA_POR_TECNICO = 4,
  ACEPTADO_POR_TECNICO = 5,
  RECHAZADO_POR_CLIENTE = 6,
  ACEPTADO_POR_CLIENTE = 7,
  CHAT_ACTIVO = 8,
  FINALIZADO_CON_VALORACION = 9,
  ELIMINADO = 10,
}
